package com.evikadar.habitsbackend.model;

public enum HabitCatName {
    FITNESS_AND_HEALTH,
    MENTAL_HEALTH,
    FAMILY_TRADITIONS,
    ENVIRONMENTAL_CONSCIOUSNESS,
    PERSONAL_GROWTH,
    CARREER_AND_SUCCESS,
    SOCIAL_CONNECTIONS,
    MONEY_CONSCIOUSNESS
}
